### PR TITLE
Share tools tweaks

### PR DESCRIPTION
**Pull request by greenc05**
Some suggestions after reviewing the work @Heydon has done on the tutorial

### CODE REVIEW

**Comment by Heydon** [comment]
@greenc05 Would you mind squashing the commits? It makes it easier to review your changes. Thanks!

**Comment by greenc05** [comment]
Please could you review when you have a moment @Heydon?

I've done some extensive AT testing... Currently when using Jaws and IE11 (Windows 7) - on the demo page when focus is moved to the 1st item in the ‘more share options’ menu, it reads out the url before reading ‘Pinterest, share this article, external’, if using the arrow keys to navigate the url isn’t read out for the other items in the menu, though if navigating via the tab key the url is read out for all the menu items before the text. I’ve tried adding role menuitem which stops the url being read out (though this then causes the item to be announced twice), though perhaps you didn’t add role menuitem in the first place for a good reason? I also notice that if adding role menuitem that you would need to add additional keyboard functionality? FYI for the same thing, it reads out ‘Number link’ before the text instead of the url when using Jaws with Chrome, adding menuitem makes it read ‘Menu’ before the text and not 'Number link'. Let me know your thoughts please.

**Comment by Heydon** [comment]
@greenc05 Thanks for the extensive tests!

> I’ve tried adding role menuitem which stops the url being read out (though this then causes the item to be announced twice), though perhaps you didn’t add role menuitem in the first place for a good reason?

I'm wondering if URLs are read out for all links in JAWS + IE11? Maybe it's a verbosity setting? 

Not all elements in the menu are strictly `menuitem`s. Adding the `menuitem` role to a link will override the link role, so the user would no longer realize it has link behavior. However, perhaps the functionality will not be that of a link in the final product, in which case this will need to be revised anyway (and probably made a generic `<button>`).

>  I also notice that if adding role menuitem that you would need to add additional keyboard functionality?

In the strict spec sense, yes! But this is a custom widget, and I have only borrowed some behaviors from the ARIA menu button pattern. A strict menu button would just have menu items, which would only affect state in the page with JavaScript. This has links, buttons and an input. The strict menu button pattern would not have a close button either, but I think this is a welcome addition in terms of clarity, and follows the GEL design.

In my experience users are not familiar with / know when to navigate by arrow key. It's generally better to just let them <kbd>Tab</kbd> as they would between simple links and buttons.

I caution the reader in the article that this pattern is custom/hybrid and point to standard menu buttons at the end. 

> Also when using Jaws and IE11 (Windows 7) in general the user experience isn't great when in the 'menu', if using the arrow keys to navigate 'menu' and 'link' are read out between every item, is this to be expected?

JAWS + Windows 7? Probably! I'm not too concerned because information is not being omitted, although I agree that it is rather verbose in this case and a bit misleading if it seems to the user that there are multiple nested menus. I think we should try omitting the menu role on the parent and replacing it with a group role plus label of "menu". It's possible JAWS/IE is getting confused by not encountering the expected `menuitem` child roles. 

> _add aria hidden true to svgs_

I remember discussing this behavior with you. Bizarre since the SVGs don't contain text. I think it's worth filing a bug with the vendor.

> _add list style type none - this stops IE from reading 'bullet'_

Good catch. I'm concerned this will stop some AT/UA combos identifying the list as a list at all, but that would be against spec, I believe, so not likely. I know that some CSS changes can add and remove semantics. Firefox used to communicate `<div>`s with `display: table` etc as actual data tables. Heuristics from hell!

**Comment by greenc05** [comment]
Thanks for the quick response @Heydon 

"I'm wondering if URLs are read out for all links in JAWS + IE11? Maybe it's a verbosity setting?" - The urls aren't read out for the exposed share icons, just the ones in the menu...

"Not all elements in the menu are strictly menuitems. Adding the menuitem role to a link will override the link role, so the user would no longer realize it has link behavior. However, perhaps the functionality will not be that of a link in the final product, in which case this will need to be revised anyway (and probably made a generic <button>)." - It would be a link in the final product...

"JAWS + Windows 7? Probably! I'm not too concerned because information is not being omitted, although I agree that it is rather verbose in this case and a bit misleading if it seems to the user that there are multiple nested menus. I think we should try omitting the menu role on the parent and replacing it with a group role plus label of "menu". It's possible JAWS/IE is getting confused by not encountering the expected menuitem child roles." - Are you ok to look at this please?

**Comment by Heydon** [comment]
@greenc05 "Are you ok to look at this please?" I have a full version of JAWS, and a Windows machine. I can try this out tomorrow :-)

**Comment by greenc05** [comment]
Fabulous, thanks @Heydon 

Shall I merge this PR in the meantime?

**Comment by Heydon** [comment]
Done!

**Comment by greenc05** [comment]
Woop woop thanks @Heydon 

When you look at this tomorrow, we/you might be able to add back in, the role list and role listitem on the nested 'menu' list if we opt for no menu role if your group solution works...

**Comment by Heydon** [comment]
@greenc05 👋
I was able to reproduce the redundant verbosity you were experiencing, so tried the `role="group"` plus `aria-label="menu"` option (ultimately I would have switched to `aria-labelledby` for translation purposes, but this was a quick test).

The result is that the current URL is no longer read out for each item focused. Why that was happening is anyone's guess, but there you go. JAWS is still a bit verbose with the group label, appending "menu" for both the input and close button, but I deem this fixed. I'll create a PR in a short while.

**Comment by Heydon** [comment]
Here it is: https://github.com/bbc/a11y-tutorials/pull/15

**Pull request merged**
